# Data is all you need

## Miroslav  Jiřík

# Goal

* How to split dataset
* Important dataset
* End to end training
* Metacentrum - Czech Computational Grid

# How to split dataset

## Training Dataset
Training Dataset: The sample of data used to fit the model.
The actual dataset that we use to train the model (weights and biases in the case of a Neural Network). The model sees and learns from this data.

## Validation Dataset
Validation Dataset: The sample of data used to provide an unbiased evaluation of a model fit on the training dataset while tuning model hyperparameters. The evaluation becomes more biased as skill on the validation dataset is incorporated into the model configuration.

The validation set is used to evaluate a given model, but this is for frequent evaluation. 

## Test Dataset
Test Dataset: The sample of data used to provide an unbiased evaluation of a final model fit on the training dataset. 

The Test dataset provides the gold standard used to evaluate the model. It is only used once a model is completely trained(using the train and validation sets). 

![train val test](https://miro.medium.com/max/1400/1*Nv2NNALuokZEcV6hYEHdGA.png)

In [ ]:

import numpy as np
from sklearn.model_selection import train_test_split

In [11]:
X, y = np.arange(10).reshape((5, 2)), range(5)
X,y

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 range(0, 5))

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

X_train, X_test, y_train, y_test

(array([[4, 5],
        [0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 [2, 0, 3],
 [1, 4])

## References 

* [Train, validation and test sets](https://towardsdatascience.com/train-validation-and-test-sets-72cb40cba9e7)
* [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

# End to end training

![traditional cv vs deep learning](https://www.researchgate.net/profile/Niall-O-Mahony/publication/331586553/figure/fig1/AS:753501407809536@1556660143025/a-Traditional-Computer-Vision-workflow-vs-b-Deep-Learning-workflow-Figure-from-8.jpg)

Taken from "Deep Learning vs. Traditional Computer Vision"



![Building block of a CNN](https://www.researchgate.net/profile/Niall-O-Mahony/publication/331586553/figure/fig2/AS:753501407817728@1556660143057/Building-blocks-of-a-CNN-Figure-from-13.ppm)


Taken from "Deep Learning vs. Traditional Computer Vision"

## Deep learning

[Teachable Machine](https://teachablemachine.withgoogle.com/)

[Detectron2 in Google Colab](https://colab.research.google.com/github/Tony607/detectron2_instance_segmentation_demo/blob/master/Detectron2_custom_coco_data_segmentation.ipynb#scrollTo=MWknKqWTWIw9)

[Detetron2 on Windows](https://github.com/mjirik/tutorials/tree/main/detectron_windows)

## References
* [Deep Learning vs. Traditional Computer Vision](http://dx.doi.org/10.1007/978-3-030-17795-9_10)

# Metacentrum

[Beginners Guide](https://wiki.metacentrum.cz/wiki/Beginners_guide)

[Jupyter for MetaCentrum Users](https://wiki.metacentrum.cz/wiki/Jupyter_for_MetaCentrum_users)

[Detectron2 on MetaCentrum](https://github.com/mjirik/tutorials/tree/main/metacentrum/detectron2_quickstart)